# print 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# Loops
# loop:
#  - 1
#  - 2
#  - 3

- name: Loop Demo
  hosts: localhost
  tasks:
    - name: Print Fruits
      ansible.builtin.debug:
        msg: "Fruit Name - {{ item }}"
      loop:
        - apple
        - banana
        - orange

# lower limit , upper limit
# 3

# 0,1,2

# 0 (iteration) -- > apple = item
# 1 ()    -> banana=item