# print 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# 1
# Loops
# loop:
#  - 1
#  - 2
#  - 3

- name: Loop Demo
  hosts: localhost
  tasks:
    - name: Print Fruits
      ansible.builtin.debug:
        msg: "Fruit Name - {{ item }}"
      loop:
        - apple
        - banana
        - orange

    - name: Print Fruits with Quantity
      ansible.builtin.debug:
        msg: "Fruit Name - {{ item.name }}, Quantity - {{ item.quantity }}"
      loop:
        - { name: apple , quantity: 10 }
        - { name: banana , quantity: 20 }
        - { name: orange , quantity: 30 }    

# lower limit , upper limit
# 3

# 0,1,2

# 0 (iteration) -- > apple = item.name ; item.quanity=10
# 1 ()    -> banana=item.name ; item.quanity=20